apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-deployment
  namespace: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart-container
        image: aryanand/docker-training:flipkart-iamge-v1.1.0
        ports:
        - containerPort: 80
