apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 190.170.20.238
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2-ad
  namespace: metallb-system
spec:
  ipAddressPools:
    - my-ip-poo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-deployment
  namespace: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart-container
        image: aryanand/docker-training:flipkart-iamge-v1.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-svc
  namespace: deployment
spec:
  type: LoadBalancer
  externalIPs:
    - 190.170.20.238       # Your public Load Balancer IP
  selector:
    app: flipkart
  ports:
    - name: lb
      port: 8087            # Port exposed on Load Balancer
      targetPort: 80      # Container Port